name: TerraAngel CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        configuration: [Release]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Get Terraria 
      run: |
        dir
        
        
    - name: Build TerraAngel
      shell: pwsh
      run: ./fast.ps1 -Download -Start

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TerraAngel_${{ matrix.os }}
        path: src/TerraAngel/Terraria/bin/${{ matrix.configuration }}/net8.0/*
